[package]
name = "map-client-factory"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0"
hex = { version = "0.4", default-features = false, features = ["alloc"]}
map-light-client = { path="../contracts" }
